name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '21' 

    - name: Install dependencies
      run: npm ci  
      working-directory: marketplace

    - name: Build
      run: npm run build  
      working-directory: marketplace

    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: marketplace/build

        
  deploy:
    needs: build
    permissions:
      pages: write      
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 